language: java
jdk:
  - oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: "gHXoEEPqFT2X+lpvMpWf/lY+VrpBojSVVHsvAARzj8w474HQ8UPmjzsDQ4lTGdOWyuplfsLiPE8KlfipOwEC9X6sW83GDZZPvhKTx4n+XalghbG5CYMdwCnUSxEvH4958jC4hvPXVf+NRfp/kP+kv1sNupRsQL5I6yJrGAAjxOYd7r2/70dR3lR23ziEhYoIVpg7MNi9xWG08YNDf7qAVC7WxvTe1eAA7m4doCewClOBvEeX5rYUxB4Y+epdkgn4Hwx3mPd4Q4/nt7GSzkB8DuVWw2L0W0LGx4Pjmh/vPbw2jsAba2wQIDwef/hQNprDEYlt5mihKOyIk4QMKsxYXOrf6ezEH6ebFyjReagZLjm+eXe64qrmXJqletF/vGRXWT8xP9JquKdflJkWf4AGfoVXeewMpNIZFh6HI4aLPui9P9Ji7zENPzLVdTTyCpJGHo6BmuGEPgfMZSNj+5RLr9EWxXiHMgBrDMj9l1XIO461voJRHZsiwURzkChK9A287pmaPaJ6w1TPW4dljLRHrVKYskFMZEwqjVNAKnzVxHEi+iMeiszMLUJ05JvSaXDnTpj0Xhmjid0NWd312B3Tyz3/nXLFK5m1iHDTRlIcztbJ4h1QBtXeaUIAmhEm+vobLGuPpDq1bFISakAM1A/HOTWToAaXYPxr+62tlnt+8WI="